### PR TITLE
Support GHC 8.8

### PR DESCRIPTION
**Pull request by ocharles**

### CODE REVIEW

**Comment by ocharles** [comment]
Rather than faffing around with MonadFail stuff, it seemed easier to just add a concrete type.

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

@sol any idea when this can get merged and pushed to hackage? My package depending on `aeson-qq` can't be added to stackage nightly until this is merged

**Comment by sol** [comment]
Hey, sorry guys for the delay!  Looking into it right now.

@ocharles thanks for the PR!

**Comment by sol** [comment]
On Hackage.

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

Thanks so much!

**Pull request merged**
